// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXlgBtmlJ6voapjooX7ojhlzOcK6S_5zs',
    appId: '1:174494369051:web:623e1f78a95ac458a4bfbe',
    messagingSenderId: '174494369051',
    projectId: 'cattle-control-app',
    authDomain: 'cattle-control-app.firebaseapp.com',
    storageBucket: 'cattle-control-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTW-zDy05GY-2E77tSizMufzupb5D4IAc',
    appId: '1:174494369051:android:6a1db0167a641cfaa4bfbe',
    messagingSenderId: '174494369051',
    projectId: 'cattle-control-app',
    storageBucket: 'cattle-control-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApKRUqLjjdB9l-lXGOsE0KGN9eLE8oYoI',
    appId: '1:174494369051:ios:cff3566581ef8900a4bfbe',
    messagingSenderId: '174494369051',
    projectId: 'cattle-control-app',
    storageBucket: 'cattle-control-app.appspot.com',
    iosClientId: '174494369051-63v58opvrm2jbc5j9l4nmeh0him40qot.apps.googleusercontent.com',
    iosBundleId: 'br.com.lucasramosleite.tccGestaoGado',
  );
}
